library(sqldf)
pc <- read.csv.sql("household_power_consumption.txt", sep=";", 'Select Date, Time, Sub_metering_1, Sub_metering_2, Sub_metering_3 from file where (Date = "1/2/2007" or Date = "2/2/2007") and  Global_active_power != "?"')
pc$Sub_metering_1 <- as.numeric(pc$Sub_metering_1)
pc$Sub_metering_2 <- as.numeric(pc$Sub_metering_2)
pc$Sub_metering_3 <- as.numeric(pc$Sub_metering_3)
pc$DateTime <- as.POSIXct(paste(pc$Date, pc$Time),format="%d/%m/%Y %H:%M:%S")
png("plot3.png")
plot(pc$DateTime, pc$Sub_metering_1, xlab="", ylab="Energy sub metering", type = "l")
lines(pc$DateTime, pc$Sub_metering_2, col="red")
lines(pc$DateTime, pc$Sub_metering_3, col="blue")
legend("topright", c("Sub metering 1", "Sub metering 2", "Sub metering 3"),lty = c(1, 1, 1), col=c("black", "red", "blue"))
dev.off()