library(sqldf)
pc <- read.csv.sql("household_power_consumption.txt", sep=";", 'Select Date, Time, Voltage, Global_active_power, Global_reactive_power, Sub_metering_1, Sub_metering_2, Sub_metering_3 from file where (Date = "1/2/2007" or Date = "2/2/2007") and  Global_active_power != "?"')
pc$Global_active_power <- as.numeric(pc$Global_active_power)
pc$Global_reactive_power <- as.numeric(pc$Global_reactive_power)
pc$Voltage <- as.numeric(pc$Voltage)
pc$Sub_metering_1 <- as.numeric(pc$Sub_metering_1)
pc$Sub_metering_2 <- as.numeric(pc$Sub_metering_2)
pc$Sub_metering_3 <- as.numeric(pc$Sub_metering_3)
pc$DateTime <- as.POSIXct(paste(pc$Date, pc$Time),format="%d/%m/%Y %H:%M:%S")
png("plot4.png")
par(mfrow=c(2,2))
plot(pc$DateTime, pc$Global_active_power, xlab="", ylab="Global Active Power (kilowatts)", type = "l")
plot(pc$DateTime, pc$Voltage, xlab="datetime", ylab="Voltage", type = "l")
plot(pc$DateTime, pc$Sub_metering_1, xlab="", ylab="Energy sub metering", type = "l")
lines(pc$DateTime, pc$Sub_metering_2, col="red")
lines(pc$DateTime, pc$Sub_metering_3, col="blue")
legend("topright", c("Sub metering 1", "Sub metering 2", "Sub metering 3"),lty = c(1, 1, 1), col=c("black", "red", "blue"))
plot(pc$DateTime, pc$Global_active_power, xlab="", ylab="Global_reactive_power", type = "l")
dev.off()